// --- DATA SOURCING (STRICT NO-FABRICATION RULE) ---
const blogPosts = []; 
const sponsorLogos = [];

// Gallery Image Placeholders
// STRICT NO-FABRICATION RULE APPLIED: Real data must be injected here.
const galleryImages = [];

const allMembers = [
  // 2026 Roster
  { name: "Airlia Vivekanand", role: "Senior Captain", year: "2026" },
  { name: "Mihir Sood", role: "Senior Captain", year: "2026" },
  { name: "Gunap Sriganesh", role: "Junior Captain", year: "2026" },
  { name: "Aditya Bhatia", role: "Mechanical Lead", year: "2026" },
  { name: "Aditya Kothuri", role: "Programming Lead", year: "2026" },
  { name: "Arnav Katewale", role: "CAD Lead", year: "2026" },
  { name: "Ayush Sharma", role: "Mechanical Lead", year: "2026" },
  { name: "Karthik Duvvuri", role: "Programming Lead", year: "2026" },
  { name: "Sathvik Surisetty", role: "Business Lead", year: "2026" },
  { name: "Siyona Vennam", role: "Media Lead", year: "2026" },
  { name: "Aadi Sanghvi", role: "Senior", year: "2026" },
  { name: "Devarsh Ganoorkar", role: "Senior", year: "2026" },
  { name: "Deveshwar Vankeswaram", role: "Senior", year: "2026" },
  { name: "Aaryan Porwal", role: "Junior", year: "2026" },
  { name: "Samarth Ramadugu", role: "Junior", year: "2026" },
  { name: "Shloka Jampula", role: "Junior", year: "2026" },
  { name: "Yohan Nguimfack", role: "Junior", year: "2026" },
  { name: "Aditya Kalisetty", role: "Sophomore", year: "2026" },
  { name: "Akuti Deepak", role: "Sophomore", year: "2026" },
  { name: "Pranav Thoppay", role: "Sophomore", year: "2026" },
  { name: "Prem Yadagiri", role: "Sophomore", year: "2026" },
  { name: "Rohit Sriram", role: "Sophomore", year: "2026" },
  { name: "Rubin Mathews", role: "Sophomore", year: "2026" },
  { name: "Ryan Samuel", role: "Sophomore", year: "2026" },
  { name: "Siddhartha Vatsa", role: "Sophomore", year: "2026" },
  { name: "Soham Padalkar", role: "Sophomore", year: "2026" },
  { name: "Tanish Chutkay", role: "Sophomore", year: "2026" },
  { name: "Keerthana Gaddam", role: "Freshman", year: "2026" },
  { name: "Krish Dasari", role: "Freshman", year: "2026" },
  { name: "Vihan Katikar", role: "Freshman", year: "2026" },
  // 2025 Roster
  { name: "Alicia Munch", role: "Senior Captain", year: "2025" },
  { name: "Sathvik Yechuri", role: "Senior Captain", year: "2025" },
  { name: "Mihir Sood", role: "Junior Captain", year: "2025" },
  { name: "Akhil Asher", role: "Programming Lead", year: "2025" },
  { name: "Akhil Chutkay", role: "Co-Mechanical Lead", year: "2025" },
  { name: "Gunap Sriganesh", role: "Co-Mechanical Lead", year: "2025" },
  { name: "Moksha Vaidya", role: "Media Lead", year: "2025" },
  { name: "Sathvik Surisetty", role: "Business Lead", year: "2025" },
  { name: "Aashi Shah", role: "Senior", year: "2025" },
  { name: "Mann Bellani", role: "Senior", year: "2025" },
  { name: "Marco Jimenez", role: "Senior", year: "2025" },
  { name: "Nayonika Sharma", role: "Senior", year: "2025" },
  { name: "Niyonika Sharma", role: "Senior", year: "2025" },
  { name: "Rithvik Sonwalkar", role: "Senior", year: "2025" },
  { name: "Samiksha Emmaneni", role: "Senior", year: "2025" },
  { name: "Sidharth Darapuram", role: "Senior", year: "2025" },
  { name: "Siri Ganapathineedi", role: "Senior", year: "2025" },
  { name: "Tania Bobbili", role: "Senior", year: "2025" },
  { name: "Aadi Sanghvi", role: "Junior", year: "2025" },
  { name: "Airlia Vivekanand", role: "Junior", year: "2025" },
  { name: "Anthony Hom", role: "Junior", year: "2025" },
  { name: "Devarsh Ganoorkar", role: "Junior", year: "2025" },
  { name: "Deveshwar Vankeswaram", role: "Junior", year: "2025" },
  { name: "Eesha Karri", role: "Junior", year: "2025" },
  { name: "Karthik Duvvuri", role: "Junior", year: "2025" },
  { name: "Aaryan Porwal", role: "Sophomore", year: "2025" },
  { name: "Arnav Katewale", role: "Sophomore", year: "2025" },
  { name: "Yohan Nguimfack", role: "Sophomore", year: "2025" },
  { name: "Aditya Bhatia", role: "Freshman", year: "2025" },
  { name: "Aditya Kalisetty", role: "Freshman", year: "2025" },
  { name: "Gowri Gurumurthy", role: "Freshman", year: "2025" },
  { name: "Prem Yadagiri", role: "Freshman", year: "2025" },
  { name: "Rubin Mathews", role: "Freshman", year: "2025" },
  { name: "Suryansh Agarwal", role: "Freshman", year: "2025" },
  { name: "Tanish Chutkey", role: "Freshman", year: "2025" },
  // 2024 Roster
  { name: "Jacob Baumel", role: "Senior Captain", year: "2024" },
  { name: "Niyonika Sharma", role: "Junior Captain", year: "2024" },
  { name: "Sathvik Yechuri", role: "Junior Captain", year: "2024" },
  { name: "Akhil Chutkay", role: "Mechanical Lead", year: "2024" },
  { name: "Alicia Munch", role: "Media Lead", year: "2024" },
  { name: "Mihir Sood", role: "Programming Lead", year: "2024" },
  { name: "Siri Ganapathineedi", role: "Business Lead", year: "2024" },
  { name: "Angel Pilli", role: "Senior", year: "2024" },
  { name: "Lakshana Natami", role: "Senior", year: "2024" },
  { name: "Aashi Shah", role: "Junior", year: "2024" },
  { name: "Akhil Asher", role: "Junior", year: "2024" },
  { name: "Mann Bellani", role: "Junior", year: "2024" },
  { name: "Marco Jimenez", role: "Junior", year: "2024" },
  { name: "Nayonika Sharma", role: "Junior", year: "2024" },
  { name: "Rithvik Sonwalkar", role: "Junior", year: "2024" },
  { name: "Samiksha Emmaneni", role: "Junior", year: "2024" },
  { name: "Sidharth Darapuram", role: "Junior", year: "2024" },
  { name: "Tania Bobbili", role: "Junior", year: "2024" },
  { name: "Aadi Sanghvi", role: "Sophomore", year: "2024" },
  { name: "Adam Singh", role: "Sophomore", year: "2024" },
  { name: "Airlia Vivekanand", role: "Sophomore", year: "2024" },
  { name: "Anthony Hom", role: "Sophomore", year: "2024" },
  { name: "Devarsh Ganoorkar", role: "Sophomore", year: "2024" },
  { name: "Deveshwar Vankeswaram", role: "Sophomore", year: "2024" },
  { name: "Karthik Duvvuri", role: "Sophomore", year: "2024" },
  { name: "Sathvik Surisetty", role: "Sophomore", year: "2024" },
  { name: "Aaryan Porwal", role: "Freshman", year: "2024" },
  { name: "Gunap Sriganesh", role: "Freshman", year: "2024" },
  // 2023 Roster
  { name: "Corey Golcman", role: "Senior Captain", year: "2023" },
  { name: "Niharika Sule", role: "Senior Captain", year: "2023" },
  { name: "Jacob Baumel", role: "Junior Captain", year: "2023" },
  { name: "Adiv Padgilwar", role: "Co-Mechanical Lead", year: "2023" },
  { name: "Angel Pilli", role: "Co-Mechanical Lead", year: "2023" },
  { name: "Nimisha Mishra", role: "Programming Lead", year: "2023" },
  { name: "Siri Ganapathineedi", role: "Business Lead", year: "2023" },
  { name: "Tania Bobbili", role: "Media Lead", year: "2023" },
  { name: "Ananya Swaminathan", role: "Junior", year: "2023" },
  { name: "Ankit Majumder", role: "Junior", year: "2023" },
  { name: "Kavin Raj", role: "Junior", year: "2023" },
  { name: "Lakshana Natamai", role: "Junior", year: "2023" },
  { name: "Akhil Chutkay", role: "Sophomore", year: "2023" },
  { name: "Alicia Munch", role: "Sophomore", year: "2023" },
  { name: "Ethan Zheng", role: "Sophomore", year: "2023" },
  { name: "George Washington - Hajnal", role: "Sophomore", year: "2023" },
  { name: "Mann Bellani", role: "Sophomore", year: "2023" },
  { name: "Niyonika Sharma", role: "Sophomore", year: "2023" },
  { name: "Rithvik Sonwalkar", role: "Sophomore", year: "2023" },
  { name: "Sathvik Yechuri", role: "Sophomore", year: "2023" },
  { name: "Sid Darapuram", role: "Sophomore", year: "2023" },
  { name: "Airlia Vivekanand", role: "Freshman", year: "2023" },
  { name: "Anthony Hom", role: "Freshman", year: "2023" },
  { name: "Mihir Sood", role: "Freshman", year: "2023" },
  { name: "Raghav Ramprasad", role: "Freshman", year: "2023" },
  { name: "Rishi Alluri", role: "Freshman", year: "2023" },
  { name: "Sathvik Surisetty", role: "Freshman", year: "2023" },
  // 2022 Roster
  { name: "Ananth Vivekanand", role: "Senior Captain", year: "2022" },
  { name: "Niharika Sule", role: "Junior Captain", year: "2022" },
  { name: "Vinay Pattanashettar", role: "Junior Captain", year: "2022" },
  { name: "Corey Golcman", role: "Mech Lead", year: "2022" },
  { name: "Jacob Baumel", role: "Programming Lead", year: "2022" },
  { name: "Joanne Ramesh", role: "Business Lead", year: "2022" },
  { name: "Siri Ganapathineedi", role: "Media Lead", year: "2022" },
  { name: "Jason Rabinowitz", role: "Senior", year: "2022" },
  { name: "Shreenidhi Ayinala", role: "Senior", year: "2022" },
  { name: "Amoolya Tadepalli", role: "Junior", year: "2022" },
  { name: "Ashwin Viswanath", role: "Junior", year: "2022" },
  { name: "Brian Bahk", role: "Junior", year: "2022" },
  { name: "Ishayu Gupta", role: "Junior", year: "2022" },
  { name: "Nikita Agarwal", role: "Junior", year: "2022" },
  { name: "Nithya Samba", role: "Junior", year: "2022" },
  { name: "Satvik Duddukuru", role: "Junior", year: "2022" },
  { name: "Tanmay Gupta", role: "Junior", year: "2022" },
  { name: "Tanya Sayooj", role: "Junior", year: "2022" },
  { name: "Deepthi Morusupalli", role: "Sophomore", year: "2022" },
  { name: "Ronit Totlani", role: "Sophomore", year: "2022" },
  { name: "Surya Rajan", role: "Sophomore", year: "2022" },
  { name: "Nayonika Sharma", role: "Freshman", year: "2022" },
  { name: "Rasya Ramakrishnan", role: "Freshman", year: "2022" },
  { name: "Tania Bobbili", role: "Freshman", year: "2022" },
  // 2021 Roster
  { name: "Ranit Gupta", role: "Senior Captain", year: "2021" },
  { name: "Samrat Sahoo", role: "Senior Captain", year: "2021" },
  { name: "Ananth Vivekanand", role: "Junior Captain", year: "2021" },
  { name: "Cooper Rogers", role: "Senior", year: "2021" },
  { name: "Ishan Gupta", role: "Senior Engineer", year: "2021" },
  { name: "Pranav Chelat", role: "Senior", year: "2021" },
  { name: "Rithvi Anakal", role: "Senior", year: "2021" },
  { name: "Ananthram Tekkalakota", role: "Junior", year: "2021" },
  { name: "Josiah Sims", role: "Junior", year: "2021" },
  { name: "Matthew Harris", role: "Junior", year: "2021" },
  { name: "Ryan Herrmann", role: "Junior", year: "2021" },
  { name: "Yash Totlani", role: "Junior", year: "2021" },
  { name: "Amoolya Tadepalli", role: "Sophomore", year: "2021" },
  { name: "Corbin Lyle", role: "Sophomore", year: "2021" },
  { name: "Corey Golcman", role: "Sophomore", year: "2021" },
  { name: "Dhruv Chanana", role: "Sophomore", year: "2021" },
  { name: "Joanne Ramesh", role: "Sophomore", year: "2021" },
  { name: "Niharika Sule", role: "Sophomore", year: "2021" },
  { name: "Tanya Sayooj", role: "Sophomore", year: "2021" },
  // 2020 Roster
  { name: "Caitlin Fukumoto", role: "Senior Captain", year: "2020" },
  { name: "Shrenik Porwal", role: "Senior Captain", year: "2020" },
  { name: "Samrat Sahoo", role: "Junior Captain", year: "2020" },
  { name: "Neha Ganapathineedi", role: "Senior", year: "2020" },
  { name: "Cooper Rogers", role: "Junior", year: "2020" },
  { name: "Ishan Gupta", role: "Junior", year: "2020" },
  { name: "Ranit Gupta", role: "Junior", year: "2020" },
  { name: "Samrat Sahoo", role: "Junior", year: "2020" },
  { name: "Vijay Karthikeyaraja", role: "Junior", year: "2020" },
  { name: "Ananth Vivekanand", role: "Sophomore", year: "2020" },
  { name: "Ananthram Tekkalakota", role: "Sophomore", year: "2020" },
  { name: "Josiah Sims", role: "Sophomore", year: "2020" },
  { name: "Matthew Harris", role: "Sophomore", year: "2020" },
  { name: "Premith Tikkani", role: "Sophomore", year: "2020" },
  { name: "Ryan Herrmann", role: "Sophomore", year: "2020" },
  { name: "Yash Totlani", role: "Sophomore", year: "2020" },
  { name: "Niharika Sule", role: "Freshman", year: "2020" },
  // 2019 Roster
  { name: "Sahil Jain", role: "Senior Captain", year: "2019" },
  { name: "Caitlin Fukumoto", role: "Junior Captain", year: "2019" },
  { name: "Abhishek Sule", role: "Senior", year: "2019" },
  { name: "Anikait Kolluri", role: "Junior", year: "2019" },
  { name: "Cassidy Wisneski", role: "Junior", year: "2019" },
  { name: "Dave Banerjee", role: "Junior", year: "2019" },
  { name: "Ishaan Guha", role: "Junior", year: "2019" },
  { name: "Ishva Patel", role: "Junior", year: "2019" },
  { name: "Neha Ganapathineedi", role: "Junior", year: "2019" },
  { name: "Shrenik Porwal", role: "Junior", year: "2019" },
  { name: "Sujay Vadlakonda", role: "Junior", year: "2019" },
  { name: "Tucker Spradley", role: "Junior", year: "2019" },
  { name: "Yesh Gutlapalli", role: "Junior", year: "2019" },
  { name: "Samrat Sahoo", role: "Sophomore", year: "2019" },
  { name: "Sierra Biddulph", role: "Sophomore", year: "2019" },
  { name: "Ananth Vivekanand", role: "Freshman", year: "2019" },
  { name: "Matthew Harris", role: "Freshman", year: "2019" }
];

export { blogPosts, sponsorLogos, galleryImages, allMembers };
