import type { Metadata } from "next";
import { HandCoins, Handshake } from "lucide-react";
import { Navbar } from "@/components/sections/navbar";
import { Footer } from "@/components/sections/footer";
import { AnimatedSection } from "@/components/ui/animated-section";
import { getSiteSettings, getSponsors } from "@/lib/cms";

export const metadata: Metadata = { title: "Sponsors | Radicubs" };

export default async function SponsorsPage() {
  const [sponsors, settings] = await Promise.all([getSponsors(), getSiteSettings()]);
  return <main><Navbar settings={settings}/><section className="page-hero"><div className="wrap"><AnimatedSection><p className="eyebrow">Support Radicubs</p><h1>Sponsors</h1><p className="section-copy">As an independent student-led team, Radicubs relies on sponsorships and community support for competition fees, materials, tools, travel, outreach, and workspace.</p></AnimatedSection></div></section><section className="section sponsor-support-section"><div className="wrap"><div className="two-col"><AnimatedSection><a className="support-card dark" data-tilt-card href={settings.donateUrl} target="_blank" rel="noreferrer"><div className="iconbox"><HandCoins size={20} strokeWidth={2.25} aria-hidden="true"/></div><h2>Donate</h2><p>Make a tax-deductible donation directly to the team.</p><span className="text-link green">Donate ↗</span></a></AnimatedSection><AnimatedSection delay={.08}><a className="support-card" data-tilt-card href="/contact"><div className="iconbox"><Handshake size={20} strokeWidth={2.25} aria-hidden="true"/></div><h2>Sponsor</h2><p>Partner with us as a corporate or individual sponsor.</p><span className="text-link green">Become a sponsor ↗</span></a></AnimatedSection></div><div style={{marginTop:80}}><p className="eyebrow">Partners</p><h2>Corporate Sponsors</h2></div><div className="corp-grid">{sponsors.corporate.map((sponsor,index)=><AnimatedSection key={sponsor.name} delay={(index%6)*.05}><a className="sponsor-card" data-tilt-card href={sponsor.href} target="_blank" rel="noreferrer"><div className="sponsor-logo"><img src={sponsor.pageLogo ?? sponsor.logo} alt={`${sponsor.name} logo`} loading="lazy" decoding="async"/></div><div className="sponsor-card-copy"><div className="post-title">{sponsor.name}</div>{sponsor.note&&<div className="post-excerpt">{sponsor.note}</div>}</div></a></AnimatedSection>)}</div><div style={{marginTop:80}}><p className="eyebrow">Community</p><h2>Individual Sponsors</h2></div><div className="individual-grid">{sponsors.individual.map((name,index)=><AnimatedSection key={name} delay={(index%8)*.03}><div className="individual" data-tilt-card>{name}</div></AnimatedSection>)}</div></div></section><Footer/></main>;
}
