/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'blog-posts': BlogPost;
    albums: Album;
    'journey-seasons': JourneySeason;
    'outreach-events': OutreachEvent;
    'team-members': TeamMember;
    'team-roles': TeamRole;
    'team-seasons': TeamSeason;
    mentors: Mentor;
    sponsors: Sponsor;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'team-seasons': {
      members: 'team-members';
    };
  };
  collectionsSelect: {
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    albums: AlbumsSelect<false> | AlbumsSelect<true>;
    'journey-seasons': JourneySeasonsSelect<false> | JourneySeasonsSelect<true>;
    'outreach-events': OutreachEventsSelect<false> | OutreachEventsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'team-roles': TeamRolesSelect<false> | TeamRolesSelect<true>;
    'team-seasons': TeamSeasonsSelect<false> | TeamSeasonsSelect<true>;
    mentors: MentorsSelect<false> | MentorsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'outreach-page': OutreachPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'outreach-page': OutreachPageSelect<false> | OutreachPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Save Draft keeps a post in the editor. Publish makes it visible on the blog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  date: string;
  /**
   * Shown on the blog list and at the top of the post.
   */
  cover?: (number | null) | Media;
  /**
   * One or two sentences shown under the title on the blog list.
   */
  excerpt?: string | null;
  /**
   * Use "Heading 2" to start each section (Mechanical, Programming, …).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Paste a YouTube link to make the card open that video instead of a post page.
   */
  youtubeVideo?: string | null;
  /**
   * Filled in from the title. The post lives at /blog/<this>.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every photo, video and file on the site. Upload here, or straight from any image field.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What's in the picture, for screen readers and search engines. e.g. "Two students wiring the robot".
   */
  alt?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Albums appear on the Gallery page, newest year first. A few photos from each also show up on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums".
 */
export interface Album {
  id: number;
  title: string;
  /**
   * Season year, used to group albums.
   */
  year?: number | null;
  /**
   * Select or drop in several photos at once. Drag to reorder.
   */
  photos?: (number | Media)[] | null;
  showOnHomepage?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-seasons".
 */
export interface JourneySeason {
  id: number;
  year: number;
  game: string;
  summary: string;
  /**
   * e.g. "21–22 official"
   */
  record: string;
  /**
   * e.g. "FIT #61"
   */
  districtRank?: string | null;
  awards?:
    | {
        award: string;
        id?: string | null;
      }[]
    | null;
  photo?: (number | null) | Media;
  photoNote?: string | null;
  tbaUrl: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * The "Where we've been" strip on the Outreach page. Drag rows to change the order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach-events".
 */
export interface OutreachEvent {
  id: number;
  _order?: string | null;
  title: string;
  year: number;
  place: string;
  /**
   * Optional. A blog post like /blog/off-season-updates, or any web address.
   */
  link?: string | null;
  photo?: (number | null) | Media;
  showWholeImage?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create each person once. Edit their profile to add a new season, keeping the old assignments. Each season has its own role and photo. Unassigned people do not appear on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * Prefills new season assignments. Existing seasons keep their saved photos.
   */
  photo?: (number | null) | Media;
  /**
   * Returning member? Add a new row here and keep the old one. Edit a row to change only that season’s role or photo. The + buttons create seasons or roles.
   */
  memberships?:
    | {
        season: number | TeamSeason;
        role: number | TeamRole;
        /**
         * Changing this photo only affects this season. Leave empty to show initials.
         */
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  identityKey?: string | null;
  mergedProfiles?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  role?: string | null;
  season?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create a season, then assign people to it in Team members. Related profiles appear below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-seasons".
 */
export interface TeamSeason {
  id: number;
  /**
   * Starting year: 2025 means the 2025–2026 robotics season.
   */
  year: number;
  title?: string | null;
  members?: {
    docs?: (number | TeamMember)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable roles for season assignments. You can also create a role from a person's role dropdown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-roles".
 */
export interface TeamRole {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Drag rows to change the order on the Mentors page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors".
 */
export interface Mentor {
  id: number;
  _order?: string | null;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Company and foundation sponsors. Drag rows to change their order. Individual and family supporters are under Settings → Site settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  _order?: string | null;
  name: string;
  website: string;
  /**
   * White or light artwork on a transparent background (the site is dark).
   */
  logo: number | Media;
  /**
   * Only if the Sponsors page should show different artwork.
   */
  pageLogo?: (number | null) | Media;
  /**
   * Only if the homepage strip needs a wider version.
   */
  wideLogo?: (number | null) | Media;
  lightLogo?: (number | null) | Media;
  lightWideLogo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can sign in and edit the website. To add someone, enter their email and a password.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'albums';
        value: number | Album;
      } | null)
    | ({
        relationTo: 'journey-seasons';
        value: number | JourneySeason;
      } | null)
    | ({
        relationTo: 'outreach-events';
        value: number | OutreachEvent;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'team-roles';
        value: number | TeamRole;
      } | null)
    | ({
        relationTo: 'team-seasons';
        value: number | TeamSeason;
      } | null)
    | ({
        relationTo: 'mentors';
        value: number | Mentor;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  youtubeVideo?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums_select".
 */
export interface AlbumsSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  photos?: T;
  showOnHomepage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-seasons_select".
 */
export interface JourneySeasonsSelect<T extends boolean = true> {
  year?: T;
  game?: T;
  summary?: T;
  record?: T;
  districtRank?: T;
  awards?:
    | T
    | {
        award?: T;
        id?: T;
      };
  photo?: T;
  photoNote?: T;
  tbaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach-events_select".
 */
export interface OutreachEventsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  year?: T;
  place?: T;
  link?: T;
  photo?: T;
  showWholeImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  memberships?:
    | T
    | {
        season?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  identityKey?: T;
  mergedProfiles?: T;
  role?: T;
  season?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-roles_select".
 */
export interface TeamRolesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-seasons_select".
 */
export interface TeamSeasonsSelect<T extends boolean = true> {
  year?: T;
  title?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors_select".
 */
export interface MentorsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  role?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  website?: T;
  logo?: T;
  pageLogo?: T;
  wideLogo?: T;
  lightLogo?: T;
  lightWideLogo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * The photos in the hero wall, in order. Photos from albums marked "Include on the homepage" are mixed in between.
   */
  wallPhotos?: (number | Media)[] | null;
  /**
   * The flip cards under "Find where you fit in". Drag to reorder.
   */
  disciplines?:
    | {
        title: string;
        copy: string;
        tags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Needs the scroll-optimised encode (frequent keyframes), or scrolling through it will stutter.
   */
  seasonVideo?: (number | null) | Media;
  seasonVideoMobile?: (number | null) | Media;
  seasonPoster?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Individual events are under Content → Outreach events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach-page".
 */
export interface OutreachPage {
  id: number;
  /**
   * Loops behind the page title.
   */
  heroVideo?: (number | null) | Media;
  heroPoster?: (number | null) | Media;
  introPhoto?: (number | null) | Media;
  stats?:
    | {
        value: number;
        /**
         * e.g. +
         */
        suffix?: string | null;
        label: string;
        plain?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The "What we run" cards.
   */
  programs?:
    | {
        title: string;
        copy: string;
        where: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Names in the scrolling partner strip.
   */
  partners?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Team details, links and supporters used across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  teamNumber?: string | null;
  location?: string | null;
  /**
   * Used for search results and link previews.
   */
  description: string;
  nonprofit?: string | null;
  applyUrl: string;
  /**
   * e.g. 2026
   */
  applicationSeason?: number | null;
  email?: string | null;
  donateUrl?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  tiktok?: string | null;
  tba?: string | null;
  /**
   * Names listed on the Sponsors page. Company sponsors are under People → Sponsors.
   */
  individualSponsors?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  wallPhotos?: T;
  disciplines?:
    | T
    | {
        title?: T;
        copy?: T;
        tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
        photo?: T;
        id?: T;
      };
  seasonVideo?: T;
  seasonVideoMobile?: T;
  seasonPoster?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach-page_select".
 */
export interface OutreachPageSelect<T extends boolean = true> {
  heroVideo?: T;
  heroPoster?: T;
  introPhoto?: T;
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        plain?: T;
        id?: T;
      };
  programs?:
    | T
    | {
        title?: T;
        copy?: T;
        where?: T;
        id?: T;
      };
  partners?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  teamNumber?: T;
  location?: T;
  description?: T;
  nonprofit?: T;
  applyUrl?: T;
  applicationSeason?: T;
  email?: T;
  donateUrl?: T;
  instagram?: T;
  linkedin?: T;
  tiktok?: T;
  tba?: T;
  individualSponsors?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}