import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { Navbar } from "@/components/sections/navbar";
import { Footer } from "@/components/sections/footer";
import { blogPosts as fallbackBlogPosts } from "@/data/blog";
import { getBlogPost, getBlogPosts, getSiteSettings } from "@/lib/cms";

export async function generateStaticParams() { const posts = await getBlogPosts(); return (posts.length ? posts : fallbackBlogPosts).map((post) => ({ slug: post.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const post = await getBlogPost(slug); return post ? { title: `${post.title} | Radicubs`, description: post.excerpt } : {}; }

export default async function BlogPostPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const [post,settings]=await Promise.all([getBlogPost(slug),getSiteSettings()]);if(!post)notFound();return <main><Navbar settings={settings}/><article className="px-6 pb-12 pt-16"><div className="mx-auto max-w-4xl"><Link href="/blog" className="hover-arrow inline-flex items-center gap-2 text-sm font-semibold text-zinc-300 hover:text-[#77ff66]"><ArrowLeft className="h-4 w-4"/>Back to blog</Link><header className="mt-10"><p className="type-meta text-xs font-medium uppercase tracking-[.16em] text-[#77ff66]">{post.date}</p><h1 className="mt-4 text-balance text-4xl font-semibold tracking-[-.02em] text-white sm:text-6xl">{post.title}</h1><p className="mt-5 text-lg leading-8 text-zinc-300">{post.excerpt}</p></header>{post.cover&&<div className="mt-10 overflow-hidden rounded-[38px] border border-white/10 bg-[rgba(16,22,18,.84)] shadow-[0_24px_80px_rgba(0,0,0,.18)]"><img src={post.cover} alt={`${post.title} cover`} className="max-h-[620px] w-full object-cover" loading="lazy" decoding="async"/></div>}<div className="prose-radicubs mt-12">{post.sections?.map((section,sectionIndex)=><section key={`${section.heading}-${sectionIndex}`} className="mb-10">{section.heading&&section.heading!=="Update"&&<h2>{section.heading}</h2>}{section.blocks&&section.blocks.length>0?section.blocks.map((block,blockIndex)=>block.kind==="text"?<p key={blockIndex}>{block.text}</p>:block.kind==="code"?<pre key={blockIndex} className="blog-code"><code>{block.code}</code></pre>:block.kind==="list"?(block.ordered?<ol key={blockIndex} className="blog-list">{block.items.map((item,i)=><li key={i}>{item}</li>)}</ol>:<ul key={blockIndex} className="blog-list">{block.items.map((item,i)=><li key={i}>{item}</li>)}</ul>):<img key={blockIndex} className="blog-figure" src={block.src} alt={block.alt} loading="lazy" decoding="async"/>):<>{section.paragraphs.map((paragraph,index)=><p key={index}>{paragraph}</p>)}{section.images&&section.images.length>0&&<div className="blog-figures">{section.images.map((image)=><img key={image.src} src={image.src} alt={image.alt} loading="lazy" decoding="async"/>)}</div>}</>}</section>)}</div>{post.sourceUrl&&<a href={post.sourceUrl} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-5 py-3 text-sm font-semibold text-zinc-100 hover:border-[#00c700]">Watch video <ArrowUpRight className="h-4 w-4"/></a>}</div></article><Footer/></main>}
