import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { Navbar } from "@/components/sections/navbar";
import { Footer } from "@/components/sections/footer";
import { blogPosts, getBlogPost } from "@/data/blog";

export async function generateStaticParams() { return blogPosts.map((post) => ({ slug: post.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const post = getBlogPost(slug); return post ? { title: `${post.title} | Radicubs`, description: post.excerpt } : {}; }

export default async function BlogPostPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const post=getBlogPost(slug);if(!post)notFound();return <main><Navbar/><article className="px-6 pb-12 pt-16"><div className="mx-auto max-w-4xl"><Link href="/blog" className="hover-arrow inline-flex items-center gap-2 text-sm font-black text-zinc-300 hover:text-[#77ff66]"><ArrowLeft className="h-4 w-4"/>Back to blog</Link><header className="mt-10"><p className="text-xs font-black uppercase tracking-[.2em] text-[#77ff66]">{post.date}</p><h1 className="mt-4 text-balance text-4xl font-black tracking-[-.05em] text-white sm:text-6xl">{post.title}</h1><p className="mt-5 text-lg leading-8 text-zinc-300">{post.excerpt}</p></header>{post.cover&&<div className="mt-10 overflow-hidden rounded-[38px] border border-white/10 bg-[rgba(16,22,18,.84)] shadow-[0_24px_80px_rgba(0,0,0,.18)]"><img src={post.cover} alt={`${post.title} cover`} className="max-h-[620px] w-full object-cover" loading="lazy" decoding="async"/></div>}<div className="prose-radicubs mt-12">{post.sections?.map((section)=><section key={section.heading} className="mb-10"><h2>{section.heading}</h2>{section.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</section>)}{!post.sections&&<div className="rounded-[30px] border border-white/10 bg-[rgba(16,22,18,.82)] p-7 shadow-[0_20px_70px_rgba(0,0,0,.14)]"><p>This archived entry is included in the rebuilt Radicubs blog index.</p></div>}</div>{post.sourceUrl&&<a href={post.sourceUrl} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-5 py-3 text-sm font-black text-zinc-100 hover:border-[#00c700]">Watch video <ArrowUpRight className="h-4 w-4"/></a>}</div></article><Footer/></main>}
